### ISSUE TITLE
[Take a picture] this._stream.stop is not a function error in Chrome

### ISSUE THREAD

**Issue by addyosmani** [imgly/imgly-sdk-html5#117]
Caused by `imglykit.min.js:69` when testing the web editor demo on https://www.photoeditorsdk.com/ and when trying to use this feature directly with the SDK locally (using master branch from a few days ago).

Steps to reproduce:

1. Open up https://www.photoeditorsdk.com/ and click on `Open HTML5 Editor`
2. Click `New` and `Take a picture`
3. Approve Chrome to use the local web cam device
2. Try to take a picture. `this._stream.stop is not a function` error displayed in console

Browsers tested on: Chrome 47 (Desktop and Android) through to Chrome 49. Verified that this is not an issue in Firefox Nightly.

If this issue has already been addressed somewhere, is it possible to link up to the commit? Trying to build out a demo for the Chrome team using your library at the moment and would love to avoid locally patching :)

**Comment by saschagehlich** [comment]
Thanks for the report Addy. Apparently the UserMedia API has changed in the
past months. I'll look into this tomorrow morning and update the repository
accordingly. Is tomorrow morning CET soon enough for you?

Caused by imglykit.min.js:69 when testing the web editor demo on
https://www.photoeditorsdk.com/ and when trying to use this feature
directly with the SDK locally (using master branch from a few days ago).

Steps to reproduce:

   1. Open up https://www.photoeditorsdk.com/ and click on Open HTML5 Editor
   2. Click New and Take a picture
   3. Approve Chrome to use the local web cam device
   4. Try to take a picture. this._stream.stop is not a function error
   displayed in console

Browsers tested on: Chrome 47 (Desktop and Android) through to Chrome 49.
Verified that this is not an issue in Firefox Nightly.

If this issue has already been addressed somewhere, is it possible to link
up to the commit? Trying to build out a demo for the Chrome team using your
library at the moment and would love to avoid locally patching :)

—
Reply to this email directly or view it on GitHub
<https://github.com/imgly/imgly-sdk-html5/issues/117>.

**Comment by addyosmani** [comment]
Absolutely :) Thank you for taking a look tomorrow!

**Comment by saschagehlich** [comment]
Hey Addy,

we just published a new release which includes a fix for the issue. We also updated the editor on our website. Here's the new release:

https://github.com/imgly/imgly-sdk-html5/releases/tag/v2.0.3-13

Thanks again!

**Comment by addyosmani** [comment]
Thanks so much for updating to support the latest getUserMedia changes. Everything works fantastic now. Appreciate the speed of getting a new release shipped :)

I believe you also pinged about feedback on the integration experience. I won't have time for a vc/hangout atm but would be happy to email over notes I look while working with your API. Would that be useful?

**Comment by sebastiandeutsch** [comment]
Hi @addyosmani - that would be awesome. Any feedback appreciated.
