### ISSUE TITLE
Radial Focus wont resize when rendering image

### ISSUE THREAD

**Issue by nicowernli** [imgly/imgly-sdk-html5#54]
When using the radialblur on an image bigger than the editor, the filter wont resize when render the final result.

**Comment by saschagehlich** [comment]
Unfortunately that's a wontfix due to the way the SDK works. The rendering is based on a stack, which means that the operations (at least when you're using the UI) are run in a specific order. Cropping and rotation are applied first, all other operations are applied on the cropped / rotated picture.
