### ISSUE TITLE
Anything that requires dragging doesn't work on Mobile (iOS or Android) e.g. Brightness, Contrast, Crop, Resize etc, etc.

### ISSUE THREAD

**Issue by liveaspankaj** [imgly/imgly-sdk-html5#8]
Anything that requires dragging doesn't work on Mobile (iOS or Android) e.g. Brightness, Contrast, Crop, Resize etc, etc.
I tested on iPad and Galaxy Note 2.

**Comment by RacZo** [comment]
Hi guys, I got to enable touch for some controls, i.e. sliders and the cropped area box, also customized the UI a lot to meet a client's design requirements but we are having issues with the imgly plugin on mobile. It always kills the browser, any recommendations about how to make it work on Mobile Safari and Chrome? Any way to compress the image in a way that the combined memory load of the image + imgly don't get so high that it crashes the mobile browser?

**Comment by RacZo** [comment]
Hey!

Thank you for the quick reply last night. We actually got it working on mobile Safari and Chrome on iOS and Chrome for Android.

No JS hacks to resize the image on the client side, that was a dead because of the memory limitations mobile browsers have (~3MB per max memory per page, 5-10 secs JS timeouts, limitations vary by handset model, RAM, platform, etc... a canvas 2d/JS nightmare!).

We decided to upload the image to the server, let the server do the heavy lifting and to return a downsized image to give it to the imgly photo editor. 

Just make sure the whole page (JS libraries, CSS, images, etc... and the dataURL in the canvas is using less than 3MB of memory and it should work.

**Comment by saschagehlich** [comment]
Dragging and touch controls in general have been re-written with the new SDK. Should work now!

**Comment by RacZo** [comment]
Awesome! I'll check it out! Thank yiu!

**Comment by RacZo** [comment]
Awesome! I'll check it out! Thank you!
